repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
          - id: isort
            additional_dependencies: [toml]
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: ""
      hooks:
          - id: flake8
